#!/bin/bash

# Site: https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md

#Efetua download do repositório github
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git

echo "source ${(q-)PWD}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ${ZDOTDIR:-$HOME}/.zshrc
